server:
  port: 8081
spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .jsp
api:
  url:
   defaultExpiryTime: 3
  # I am keeping 1 day -> and urlExpiry Time in seconds
